version: "3.5"

services:
  frontend:
    image: frontend_part210
    ports:
      - 5000:5000
  backend:
    image: backend_part210
    ports:
    - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
  redis:
    image: redis
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
  nginx:
    image: nginx
    ports:
    - 80:80
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
