FROM openjdk:8

EXPOSE 8080

WORKDIR /usr/src/app

# Copy all of the content from the project to the image
COPY . /usr/src/app

# Install
RUN ./mvnw package

# And finally the command to run the application
CMD ["java", "-jar", "./target/docker-example-1.1.3.jar"]
