version: "3.5"

services:
  frontend:
    build: ./ml-kurkkumopo-frontend
    ports:
      - 3000:3000
  backend:
    build: ./ml-kurkkumopo-backend
    ports:
    - 5000:5000
    volumes:
    - ./training/model:/src/model
  training:
    build: ./ml-kurkkumopo-training
    volumes:
      - ./training/imgs:/src/imgs
      - ./training/model:/src/model

